In [318]:
import pandas as pd

In [319]:
df_sold = pd.read_csv("CRMLSSold.csv", low_memory = False)
df_listing = pd.read_csv("CRMLSListing.csv", low_memory = False)

In [320]:
# Both lists contain the same values, just in different orders.
print(f"Property Types (CRMLSSold): {df_sold["PropertyType"].unique()}")
print(f"Property Types (CRMLSListing): {df_listing["PropertyType"].unique()}")

Property Types (CRMLSSold): ['Residential' 'Land' 'ManufacturedInPark' 'ResidentialIncome'
 'ResidentialLease' 'CommercialSale' 'CommercialLease'
 'BusinessOpportunity']
Property Types (CRMLSListing): ['Land' 'Residential' 'ResidentialLease' 'CommercialSale'
 'ManufacturedInPark' 'BusinessOpportunity' 'CommercialLease'
 'ResidentialIncome']

In [321]:
print("Residential Property Type Share")
print(f"- CRMLSSold: {len(df_sold[df_sold.PropertyType == "Residential"]) / len(df_sold) * 100:.3f}%")
print(f"- CRMLSListing: {len(df_listing[df_listing.PropertyType == "Residential"]) / len(df_listing) * 100:.3f}%")

Residential Property Type Share
- CRMLSSold: 66.851%
- CRMLSListing: 65.873%

In [322]:
df_sold = df_sold[df_sold.PropertyType == "Residential"]
df_listing = df_listing[df_listing.PropertyType == "Residential"]

In [323]:
print("CRMLSSold Dataset")
print(f"- Rows: {len(df_sold)}")
print(f"- Columns: {len(df_sold.columns)}\n")

print("CRMLSListing Dataset")
print(f"- Rows: {len(df_listing)}")
print(f"- Columns: {len(df_listing.columns)}")

CRMLSSold Dataset
- Rows: 438115
- Columns: 79

CRMLSListing Dataset
- Rows: 480383
- Columns: 81

In [324]:
print("Missing Counts/Percentages (CRMLSSold)")

for column in df_sold:
    na_count = df_sold[column].isna().sum()
    na_percent = na_count / len(df_sold) * 100
    na_flag = ""
    if na_percent > 90:
        na_flag = " - [>90% MISSING VALUES]"
    print(f"- {column}: {na_count} ({na_percent:.3f}%){na_flag}")

Missing Counts/Percentages (CRMLSSold)
- BuyerAgentAOR: 22648 (5.169%)
- ListAgentAOR: 58 (0.013%)
- Flooring: 158591 (36.198%)
- ViewYN: 38628 (8.817%)
- WaterfrontYN: 437839 (99.937%) - [>90% MISSING VALUES]
- BasementYN: 429561 (98.048%) - [>90% MISSING VALUES]
- PoolPrivateYN: 32764 (7.478%)
- OriginalListPrice: 902 (0.206%)
- ListingKey: 0 (0.000%)
- CloseDate: 0 (0.000%)
- ClosePrice: 2 (0.000%)
- ListAgentFirstName: 2880 (0.657%)
- ListAgentLastName: 55 (0.013%)
- Latitude: 53502 (12.212%)
- Longitude: 53502 (12.212%)
- UnparsedAddress: 468 (0.107%)
- PropertyType: 0 (0.000%)
- LivingArea: 262 (0.060%)
- ListPrice: 0 (0.000%)
- DaysOnMarket: 0 (0.000%)
- ListOfficeName: 0 (0.000%)
- BuyerOfficeName: 5953 (1.359%)
- CoListOfficeName: 337792 (77.101%)
- ListAgentFullName: 134 (0.031%)
- CoListAgentFirstName: 338113 (77.174%)
- CoListAgentLastName: 337867 (77.118%)
- BuyerAgentMlsId: 551 (0.126%)
- BuyerAgentFirstName: 1938 (0.442%)
- BuyerAgentLastName: 217 (0.050%)
- FireplacesTotal: 438115 (100.000%) - [>90% MISSING VALUES]
- AssociationFeeFrequency: 253591 (57.882%)
- AboveGradeFinishedArea: 438115 (100.000%) - [>90% MISSING VALUES]
- ListingKeyNumeric: 0 (0.000%)
- MLSAreaMajor: 60121 (13.723%)
- TaxAnnualAmount: 438115 (100.000%) - [>90% MISSING VALUES]
- CountyOrParish: 0 (0.000%)
- MlsStatus: 0 (0.000%)
- ElementarySchool: 382456 (87.296%)
- AttachedGarageYN: 68355 (15.602%)
- ParkingTotal: 416 (0.095%)
- BuilderName: 415634 (94.869%) - [>90% MISSING VALUES]
- PropertySubType: 835 (0.191%)
- LotSizeAcres: 34715 (7.924%)
- SubdivisionName: 272392 (62.174%)
- BuyerOfficeAOR: 23126 (5.279%)
- YearBuilt: 399 (0.091%)
- StreetNumberNumeric: 560 (0.128%)
- ListingId: 0 (0.000%)
- BathroomsTotalInteger: 70 (0.016%)
- City: 268 (0.061%)
- TaxYear: 438115 (100.000%) - [>90% MISSING VALUES]
- BuildingAreaTotal: 406531 (92.791%) - [>90% MISSING VALUES]
- BedroomsTotal: 12 (0.003%)
- ContractStatusChangeDate: 572 (0.131%)
- ElementarySchoolDistrict: 438115 (100.000%) - [>90% MISSING VALUES]
- CoBuyerAgentFirstName: 397782 (90.794%) - [>90% MISSING VALUES]
- PurchaseContractDate: 238 (0.054%)
- ListingContractDate: 1 (0.000%)
- BelowGradeFinishedArea: 435527 (99.409%) - [>90% MISSING VALUES]
- BusinessType: 438115 (100.000%) - [>90% MISSING VALUES]
- StateOrProvince: 0 (0.000%)
- CoveredSpaces: 438115 (100.000%) - [>90% MISSING VALUES]
- MiddleOrJuniorSchool: 381939 (87.178%)
- FireplaceYN: 372 (0.085%)
- Stories: 62052 (14.163%)
- HighSchool: 364604 (83.221%)
- Levels: 36440 (8.317%)
- LotSizeDimensions: 416389 (95.041%) - [>90% MISSING VALUES]
- LotSizeArea: 34125 (7.789%)
- MainLevelBedrooms: 182715 (41.705%)
- NewConstructionYN: 33493 (7.645%)
- GarageSpaces: 19413 (4.431%)
- HighSchoolDistrict: 124177 (28.343%)
- PostalCode: 3 (0.001%)
- AssociationFee: 98312 (22.440%)
- LotSizeSquareFeet: 34259 (7.820%)
- MiddleOrJuniorSchoolDistrict: 438115 (100.000%) - [>90% MISSING VALUES]
- OriginatingSystemName: 0 (0.000%)
- OriginatingSystemSubName: 0 (0.000%)

In [325]:
na_count = []
na_percent = []
na_flag = []

for column in df_sold:
    na_count_num = df_sold[column].isna().sum()
    na_count.append(na_count_num)
    na_percent_num = na_count_num / len(df_sold) * 100
    na_percent.append(na_percent_num)
    if na_percent_num > 90:
        na_flag.append(1)
    else:
        na_flag.append(0)

null_summary_sold = pd.DataFrame({"ColumnName": df_sold.columns,
                     "MissingCount": na_count,
                     "MissingPercent": na_percent,
                     "Flag": na_flag})

# "Flag" is a boolean that corresponds to whether MissingPercent is greater than 90.
null_summary_sold[null_summary_sold.Flag == 1]

                      ColumnName  MissingCount  MissingPercent  Flag
4                   WaterfrontYN        437839       99.937003     1
5                     BasementYN        429561       98.047545     1
29               FireplacesTotal        438115      100.000000     1
31        AboveGradeFinishedArea        438115      100.000000     1
34               TaxAnnualAmount        438115      100.000000     1
40                   BuilderName        415634       94.868699     1
50                       TaxYear        438115      100.000000     1
51             BuildingAreaTotal        406531       92.790934     1
54      ElementarySchoolDistrict        438115      100.000000     1
55         CoBuyerAgentFirstName        397782       90.793970     1
58        BelowGradeFinishedArea        435527       99.409288     1
59                  BusinessType        438115      100.000000     1
61                 CoveredSpaces        438115      100.000000     1
67             LotSizeDimensions        416389       95.041028     1
76  MiddleOrJuniorSchoolDistrict        438115      100.000000     1

In [326]:
print("Missing Counts/Percentages (CRMSListing)")

for column in df_listing:
    na_count = df_listing[column].isna().sum()
    na_percent = na_count / len(df_listing) * 100
    na_flag = ""
    if na_percent > 90:
        na_flag = " - [>90% MISSING VALUES]"
    print(f"- {column}: {na_count} ({na_percent:.3f}%){na_flag}")

Missing Counts/Percentages (CRMSListing)
- OriginalListPrice: 900 (0.187%)
- ListingKey: 0 (0.000%)
- CloseDate: 57714 (12.014%)
- ClosePrice: 59676 (12.423%)
- ListAgentFirstName: 3147 (0.655%)
- ListAgentLastName: 56 (0.012%)
- Latitude: 49207 (10.243%)
- Longitude: 49207 (10.243%)
- UnparsedAddress: 561 (0.117%)
- PropertyType: 0 (0.000%)
- LivingArea: 327 (0.068%)
- ListPrice: 0 (0.000%)
- DaysOnMarket: 0 (0.000%)
- ListOfficeName: 0 (0.000%)
- BuyerOfficeName: 63793 (13.280%)
- CoListOfficeName: 370396 (77.104%)
- ListAgentFullName: 141 (0.029%)
- CoListAgentFirstName: 370760 (77.180%)
- CoListAgentLastName: 370467 (77.119%)
- BuyerAgentMlsId: 58621 (12.203%)
- BuyerAgentFirstName: 59935 (12.477%)
- BuyerAgentLastName: 58299 (12.136%)
- FireplacesTotal: 480383 (100.000%) - [>90% MISSING VALUES]
- AssociationFeeFrequency: 275641 (57.379%)
- AboveGradeFinishedArea: 480383 (100.000%) - [>90% MISSING VALUES]
- ListingKeyNumeric: 0 (0.000%)
- MLSAreaMajor: 65776 (13.692%)
- TaxAnnualAmount: 480383 (100.000%) - [>90% MISSING VALUES]
- CountyOrParish: 0 (0.000%)
- PropertyType.1: 0 (0.000%)
- MlsStatus: 0 (0.000%)
- ElementarySchool: 420168 (87.465%)
- ListAgentFirstName.1: 3147 (0.655%)
- AttachedGarageYN: 77289 (16.089%)
- ParkingTotal: 14 (0.003%)
- BuilderName: 456644 (95.058%) - [>90% MISSING VALUES]
- PropertySubType: 945 (0.197%)
- LotSizeAcres: 37850 (7.879%)
- SubdivisionName: 299790 (62.406%)
- BuyerOfficeAOR: 81956 (17.061%)
- YearBuilt: 531 (0.111%)
- DaysOnMarket.1: 0 (0.000%)
- StreetNumberNumeric: 674 (0.140%)
- LivingArea.1: 327 (0.068%)
- ListingId: 0 (0.000%)
- BathroomsTotalInteger: 67 (0.014%)
- City: 313 (0.065%)
- TaxYear: 480383 (100.000%) - [>90% MISSING VALUES]
- BuildingAreaTotal: 444086 (92.444%) - [>90% MISSING VALUES]
- BedroomsTotal: 110 (0.023%)
- ContractStatusChangeDate: 977 (0.203%)
- Longitude.1: 49207 (10.243%)
- ElementarySchoolDistrict: 480383 (100.000%) - [>90% MISSING VALUES]
- CoBuyerAgentFirstName: 441273 (91.859%) - [>90% MISSING VALUES]
- PurchaseContractDate: 41960 (8.735%)
- ListingContractDate: 0 (0.000%)
- BelowGradeFinishedArea: 477418 (99.383%) - [>90% MISSING VALUES]
- BusinessType: 480383 (100.000%) - [>90% MISSING VALUES]
- Latitude.1: 49207 (10.243%)
- ListPrice.1: 0 (0.000%)
- StateOrProvince: 49 (0.010%)
- CoveredSpaces: 480383 (100.000%) - [>90% MISSING VALUES]
- MiddleOrJuniorSchool: 419771 (87.383%)
- FireplaceYN: 431 (0.090%)
- Stories: 69833 (14.537%)
- HighSchool: 400916 (83.458%)
- Levels: 40606 (8.453%)
- ListAgentLastName.1: 56 (0.012%)
- CloseDate.1: 57714 (12.014%)
- LotSizeDimensions: 456296 (94.986%) - [>90% MISSING VALUES]
- LotSizeArea: 37159 (7.735%)
- MainLevelBedrooms: 201747 (41.997%)
- NewConstructionYN: 36478 (7.594%)
- GarageSpaces: 22400 (4.663%)
- HighSchoolDistrict: 137531 (28.629%)
- PostalCode: 11 (0.002%)
- BuyerOfficeName.1: 63793 (13.280%)
- AssociationFee: 107460 (22.370%)
- LotSizeSquareFeet: 37314 (7.768%)
- MiddleOrJuniorSchoolDistrict: 480383 (100.000%) - [>90% MISSING VALUES]
- UnparsedAddress.1: 561 (0.117%)

In [327]:
na_count = []
na_percent = []
na_flag = []

for column in df_listing:
    na_count_num = df_listing[column].isna().sum()
    na_count.append(na_count_num)
    na_percent_num = na_count_num / len(df_listing) * 100
    na_percent.append(na_percent_num)
    if na_percent_num > 90:
        na_flag.append(1)
    else:
        na_flag.append(0)

null_summary_listing = pd.DataFrame({"ColumnName": df_listing.columns,
                     "MissingCount": na_count,
                     "MissingPercent": na_percent,
                     "Flag": na_flag})

# "Flag" is a boolean that corresponds to whether MissingPercent is greater than 90.
null_summary_listing[null_summary_listing.Flag == 1]

                      ColumnName  MissingCount  MissingPercent  Flag
22               FireplacesTotal        480383      100.000000     1
24        AboveGradeFinishedArea        480383      100.000000     1
27               TaxAnnualAmount        480383      100.000000     1
35                   BuilderName        456644       95.058318     1
47                       TaxYear        480383      100.000000     1
48             BuildingAreaTotal        444086       92.444154     1
52      ElementarySchoolDistrict        480383      100.000000     1
53         CoBuyerAgentFirstName        441273       91.858580     1
56        BelowGradeFinishedArea        477418       99.382784     1
57                  BusinessType        480383      100.000000     1
61                 CoveredSpaces        480383      100.000000     1
69             LotSizeDimensions        456296       94.985876     1
79  MiddleOrJuniorSchoolDistrict        480383      100.000000     1

In [328]:
df_sold[["ClosePrice", "LivingArea", "DaysOnMarket"]].describe().style.format("{:,.3f}")

In [330]:
df_listing[["ClosePrice", "LivingArea", "DaysOnMarket"]].describe().style.format("{:,.3f}")

In [335]:
df_sold.to_csv("CRMLSSold (v2).csv", index = False)
df_listing.to_csv("CRMLSListing (v2).csv", index = False)

In [332]:
# Numeric Distribution Review (WIP)
key_numeric_fields = ["ClosePrice", "ListPrice", "OriginalListPrice", "LivingArea", "LotSizeAcres", "BedroomsTotal", "BathroomsTotalInteger", "DaysOnMarket", "YearBuilt"]

In [333]:
df_sold[key_numeric_fields].describe().loc[["25%", "50%", "75%"]].style.format("{:,.3f}")

In [334]:
df_listing[key_numeric_fields].describe().loc[["25%", "50%", "75%"]].style.format("{:,.3f}")