In [121]:
import pandas as pd

In [122]:
df_sold = pd.read_csv("CRMLSSold_3.csv", low_memory = False)
df_listings = pd.read_csv("CRMLSListing_3.csv", low_memory = False)

In [123]:
df_sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName,year_month,rate_30yr_fixed
0,ContraCosta,ContraCosta,"Tile,Wood",NaN,False,5000000.0,1095075487,2024-01-18,5000000.0,Erin,...,False,3.0,NaN,94595,NaN,30240.0,CRMLS,CRMLS_CCBE,2024-01,6.6425
1,NaN,Mlslistings,NaN,False,NaN,NaN,1079166779,2024-01-30,858000.0,David,...,False,2.0,Palm Springs Unified,92262,NaN,13504.0,CRMLS,CRMLS_MLSL,2024-01,6.6425
2,Glendale,Southland,NaN,False,False,1890500.0,1075037759,2024-01-29,1890500.0,Karen,...,False,2.0,Los Angeles Unified,91356,0.0,17873.0,CRMLS,CRMLS_CRM,2024-01,6.6425
3,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,2024-01-02,2100000.0,Jennifer,...,False,3.0,San Luis Coastal Unified,93401,0.0,11219.0,CRMLS,CRMLS_CRM,2024-01,6.6425
4,CoastalMendocino,CoastalMendocino,Tile,True,False,1950000.0,1063453216,2024-01-22,1950000.0,Kira,...,NaN,2.0,NaN,95437,NaN,74487.6,CRMLS,CRMLS_CRF,2024-01,6.6425

In [124]:
df_listings.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1,year_month,rate_30yr_fixed
0,759000.0,1159972295,NaN,NaN,Richard,Sirois,33.738910,-116.198447,42680 Incantata Place,Residential,...,False,2.0,Desert Sands Unified,92203,NaN,289.0,5227.0,42680 Incantata Place,2024-01,6.6425
1,320000.0,1159871345,2026-05-11,320000.0,Nicholas,Miller,33.842793,-116.481803,28388 Desert Princess Drive,Residential,...,False,1.0,NaN,92234,Coldwell Banker Realty,855.0,1307.0,28388 Desert Princess Drive,2024-01,6.6425
2,115900.0,1153320466,2026-04-10,160000.0,Heidi,Dunk-Vincent,39.125903,-122.861472,6900 Glenn,Residential,...,False,1.0,Upper Lake Union,95464,Noble Realty,0.0,3920.0,6900 Glenn,2024-01,6.6425
3,2500000.0,1146529264,2026-04-17,2000000.0,Clifford,Stevens,34.150964,-118.390267,4415 Morella Ave,Residential,...,False,2.0,Los Angeles Unified,91607,Equity Union,0.0,9906.0,4415 Morella Ave,2024-01,6.6425
4,3200000.0,1118382573,2025-05-21,3200000.0,Trudy,McGrath,33.028788,-117.264434,1200 Cardiff Drive,Residential,...,False,0.0,San Dieguito Union,92024,NonMember/Member-Other Board,0.0,54885.6,1200 Cardiff Drive,2024-01,6.6425

In [125]:
# Document every transformation you made & why.

In [126]:
# Row Counts (BEFORE)
print("Row Counts (BEFORE):")
print(f"- Sold: {len(df_sold)}")
print(f"- Listings: {len(df_listings)}")

Row Counts (BEFORE):
- Sold: 455658
- Listings: 504466

In [127]:
# Data Type Confirmations (BEFORE)
sold_dtypes = sorted(df_sold.dtypes.unique().astype(str).tolist())
listings_dtypes = sorted(df_listings.dtypes.unique().astype(str).tolist())

print("Data Type Confirmations (BEFORE):")
print(f"- Sold: {sold_dtypes}")
print(f"- Listings: {listings_dtypes}")

Data Type Confirmations (BEFORE):
- Sold: ['float64', 'int64', 'object']
- Listings: ['float64', 'int64', 'object']

In [128]:
# Convert date fields to datetime format: CloseDate, PurchaseContractDate, ListingContractDate, ContractStatusChangeDate
date_fields = ["CloseDate", "PurchaseContractDate", "ListingContractDate", "ContractStatusChangeDate"]

for field in date_fields:
    df_sold[field] = pd.to_datetime(df_sold[field])
    df_listings[field] = pd.to_datetime(df_listings[field])

In [6]:
# Remove unnecessary or redundant columns

In [7]:
# Handle missing values appropritately

In [8]:
# Ensure numeric fields are properly typed

In [9]:
# Remove or flag invalid numeric values:
## ClosePrice <= 0
## LivingArea <= 0
## DaysOnMarket < 0
## negative Bedrooms or Bathrooms

In [119]:
# Validate the logical order of date fields:
## - ListingContractDate should precede PurchaseContractDate
## - PurchaseContractDate should precede CloseDate
# Create boolean flag columns to mark records that violate these rules:
## - listing_after_close_flag
## - purchase_after_close_flag
## - negative_timeline_flag

In [120]:
# Flag records with missing coordinates (Latitude or Longitude is null)
# Flag Latitude = 0 or Longitude = 0 (sentinel null values)
# Flag Longitude > 0 errors (California coordinates should be negative)
# Flag out-of-state or implausible coordinates

In [129]:
# Row Counts (AFTER)
print("Row Counts (AFTER):")
print(f"- Sold: {len(df_sold)}")
print(f"- Listings: {len(df_listings)}")

Row Counts (AFTER):
- Sold: 455658
- Listings: 504466

In [130]:
# Data Type Confirmations (AFTER)
sold_dtypes = sorted(df_sold.dtypes.unique().astype(str).tolist())
listings_dtypes = sorted(df_listings.dtypes.unique().astype(str).tolist())

print("Data Type Confirmations (AFTER):")
print(f"- Sold: {sold_dtypes}")
print(f"- Listings: {listings_dtypes}")

Data Type Confirmations (AFTER):
- Sold: ['datetime64[ns]', 'float64', 'int64', 'object']
- Listings: ['datetime64[ns]', 'float64', 'int64', 'object']

In [ ]:
# df_sold.to_csv("CRMLSSold_4.csv", index = False)
# df_listings.to_csv("CRMLSListing_4.csv", index = False)